---
- name: Create a folder on the desktop
  hosts:  3.110.84.87
  become: yes  

  tasks:
    - name: Create the folder on the desktop
      file:
        path: /home/ubuntu
        state: directory
      become_user: anurag  
