---
- name: Create a folder on the desktop, update apt cache, and install tree
  hosts: 192.168.88.69
  become: yes

  tasks:
    - name: Create the folder on the desktop
      file:
        path: /home/fintech/Desktop/new_folder3
        state: directory
      become_user: fintech

    - name: Install tree via snap
      command: sudo snap install tree
      become_user:  fintech
