---
- name: Create a folder on the desktop
  hosts: your_target_host  # Replace with the hostname or IP address of your Ubuntu machine
  become: yes  # This enables privilege escalation (sudo)

  tasks:
    - name: Create the folder on the desktop
      file:
        path: ~/Desktop/my_folder  # Change 'my_folder' to your desired folder name
        state: directory
      become_user: anurag  # Replace with your Ubuntu username
