---
- name: Create a folder on the desktop
  hosts:  192.168.88.69
  become: yes  

  tasks:
    - name: Create the folder on the desktop
      file:
        path: /home/fintech/Desktop/new_folder2
        state: directory
      become_user: fintech
      
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Apache2 package (HTTP server)
      apt:
        name: apache2
        state: latest  # This ensures the latest version is installed

    - name: Ensure Apache2 service is running
      service:
        name: apache2
        state: started   
