---
- name: Create a folder on the desktop, update apt cache, and install tree
  hosts: 192.168.88.69
  become: yes

  tasks:
    - name: Create the folder on the desktop
      file:
        path: /home/fintech/Desktop/new_folder2
        state: directory
      become_user: fintech

    - name: Update apt package cache
      apt:
        update_cache: yes
      become: yes

    - name: Install tree package
      apt:
        name: tree
        state: present
      become: yes

