---
- name: Create a folder on the desktop
  hosts:  192.168.88.69
  become: yes  

  tasks:
    - name: Create the folder on the desktop
      file:
        path: /home/anurag/Desktop/my_folder2
        state: directory
      become_user: anurag  
